language: generic
sudo: required
dist: trusty
services:
- docker
before_script:
- printenv | awk -F= '{if ($1 ~ /^(TRAVIS|GITHUB)/) print $1"="$2}' > .env
- docker-compose build web
script:
- docker-compose run web typesafety --review
- docker-compose run web composer test
matrix:
  fast_finish: true
notifications:
  email: false
env:
  global:
  - secure: ofo6sB/GWwyY7Xaqv9GEFiZzj1VwTSyiaZnhBMjb03grCUNAegwtd7+ja+tM1QZcZPE5wNlrwue0d2awARVYvi8ItAcrRxj6ijBCfdEWqwokJTODk2alzM+ecotGlWKs9j+c0+uB72l/D0+NqC43Pndeue6Fa6eeEOCaXdfDRRR6r4uJRu7jG2r0uyuQ/F7Jqzp2WZYQ/Ce4G47HhDAK4Jc9A6NPkxngk/JXR/rYCY34uNaUQ7KKArRt8pqhhkMSVRtTCgW57d3TZCvpSokQ4O/l1cYWjcuBTPktx5WXebBO21IeZYH1tArwFCCWY8hJT834wNwjwdz4ClVsUm0382ekJCbKLtGxJwUI0S5xNvPXwc1hp2FpkzhlWfZItyVeDdjq+w08nPik6m6WPtLgpisvRXnummNc72NPwrfnsD2YkFyfT+RUdv/ANuPWNtNEkBJ/bD1tlbUkh91pw3w9G+BG7CPOLlUhnooXxoB88TjOgnnv85wwq9iJmc7Cjg14jgnnn+exrgQL3jgI3rJgw2FP2N0xC4vynhI1r+T2xQSI/aPukUShrC6AFP3N4/3/fX//LRwSzePbwOC9qmqfuK5nW9T2vmq8vI0YtQK8xqq+d9u5DIi6otH5OfMl5RRVl5Vd+vC6eFELUblN8lsuHHtwcBYv/9AdT1YG4sh96bQ=
  - secure: J9pPsktlTjQEKEltKvrQMdq99qouDPSL1c+CYWotgc/5FCUGguwTdLjrBuvALlXX9F6D3a1ZzgdK5IZBbXxlXllt/X+DWd6LQ80EV+/Tv9xM0h5w8V3CmdgspHezMT+bupQ4OrDnhk4IgvvU7CC6ODDTHZELWie45Ygg0VcXicans/lB0YiuTBfOsFF6YH/vgrgN3HkGjwoDUAHY04o4Ik4CGpXNuJoBYjk3BWAZcjeQrwRbyqlSws/uCv0eoMLkjp4uRklH6AuNrwpCZhD99wchsLEwfoon2iGMFGBMiypdbvxxP51xgw1YUfRhiEy3DVUlgZTVSntbzFvVTTYJ3dFh6xN7GVV/RRIQxE87G09sH4i6/D49qeV7dAsDBDOUPtUU+d3MUR4QQT9fqZlxGDLIILxC3IK9tErOgSZsKp1fKy/26zo1i3lunmTSoFTWKtLShcwF9xpwNb3QjCRchZC+vjDGXFVB8z4Qjoo5JtZQTeWAZqQiwTPdEI3LFoOaKal9Wrf7IpYrfaYZEUSVhMEjepH9Q5Ytd34QzJRj4pjv8P/JL60q0KI2UrWBvOwTkESAA2ZgTG51f3zpkB0ZwcxDvDrQFGjcBVBBVZRIBi/GkkyAU2iVIRPeZJfhObB4KoaGzAC4jSciOCSxbPzjCufZQd49wqlY9daEr/a5NsI=
