version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build docker images
          command: docker-compose build web
      - run:
          name: typecheck by typesafety-cli
          command: docker-compose run web typesafety --review
      - run:
          name: execute test
          command: docker-compose run web composer test
